name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: biblioteca
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      # Configurar JDK 21 (compatível com o Dockerfile)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configurar Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Cache do Gradle para acelerar builds
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Conceder permissão de execução para gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Configurar variáveis de ambiente do MySQL
      - name: Configurar variáveis de ambiente
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/biblioteca" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=root" >> $GITHUB_ENV 

      # Aguardar MySQL estar pronto antes de rodar os testes
      - name: Aguardar MySQL estar pronto
        run: |
          echo "Aguardando MySQL iniciar..."
          for i in {1..30}; do
            mysqladmin ping --host=127.0.0.1 --user=root --password=root && break
            echo "MySQL ainda não está pronto... tentando novamente..."
            sleep 2
          done

      # Build e execução dos testes com Gradle
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Configurar JDK 21 para análise de dependências
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
