# This workflow builds a Java project with Gradle, runs tests, and publishes a Docker image.

name: Java CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: biblioteca
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching dependencies.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Verificar status do MySQL antes dos testes
        run: |
          sudo apt-get install -y mysql-client
          mysql --host=127.0.0.1 --user=root --password=root -e "SHOW DATABASES;"

      # ✅ Adicionando permissão de execução para o gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configurar variáveis de ambiente
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/biblioteca" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=root" >> $GITHUB_ENV 

      # Compilar o projeto com Gradle Wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  docker:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da Imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/biblioteca:latest .

      - name: Push da Imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/biblioteca:latest

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Gera e envia o gráfico de dependências para ativar Dependabot Alerts
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
